// Generates the Blade contract table in docs/component-policy.md from docs/component-catalog.json.
// Usage: node scripts/build-docs.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const policyFile = new URL('docs/component-policy.md', root);
const start = '<!-- contracts:start (generated by scripts/build-docs.mjs from component-catalog.json) -->';
const end = '<!-- contracts:end -->';

export function contractTable(catalog) {
  const rows = catalog
    .flatMap(entry => Object.entries(entry.contracts || {}))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, c]) => `| \`${name}\` | ${c.purpose} | ${c.element} | ${c.state} | ${c.keyboard} | ${c.options} |`);
  return [
    '| Component | Purpose | Native element and role | Value or state | Keyboard | Options and slots |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function renderPolicy(policy, catalog) {
  const from = policy.indexOf(start),
    to = policy.indexOf(end);
  if (from < 0 || to < from) throw new Error('component-policy.md needs the generated contract markers.');
  return `${policy.slice(0, from + start.length)}\n${contractTable(catalog)}\n${policy.slice(to)}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const catalog = JSON.parse(readFileSync(new URL('docs/component-catalog.json', root), 'utf8'));
  const policy = readFileSync(policyFile, 'utf8');
  const rendered = renderPolicy(policy, catalog);
  if (process.argv.includes('--check')) {
    if (rendered !== policy) {
      console.error('docs/component-policy.md is out of date. Run npm run build:docs.');
      process.exit(1);
    }
  } else {
    writeFileSync(policyFile, rendered);
  }
}
